<a href="https://colab.research.google.com/github/PALLADIUM26/ML/blob/main/ML5_knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

5.	Using KNN algorithm, predict which category a customer belongs to on the basis of the data provided by a telecommunications firm. Find the accuracy of the KNN algorithm in predicting the category of a customer.
Dataset: teleCust.csv


In [ ]:
# Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [ ]:
#Metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import jaccard_score
from sklearn.metrics import roc_curve

In [ ]:
data=pd.read_csv('teleCust.csv')
raw = data.copy()
data.shape

(1000, 12)

In [ ]:
data.head()

region  tenure  age  marital  address  income  ed  employ  retire  gender  \
0       2      13   44        1        9    64.0   4       5     0.0       0   
1       3      11   33        1        7   136.0   5       5     0.0       0   
2       3      68   52        1       24   116.0   1      29     0.0       1   
3       2      33   33        0       12    33.0   2       0     0.0       1   
4       2      23   30        1        9    30.0   1       2     0.0       0   

   reside  custcat  
0       2        1  
1       6        4  
2       2        3  
3       1        1  
4       4        3

In [ ]:
data.describe()

region       tenure          age      marital      address  \
count  1000.0000  1000.000000  1000.000000  1000.000000  1000.000000   
mean      2.0220    35.526000    41.684000     0.495000    11.551000   
std       0.8162    21.359812    12.558816     0.500225    10.086681   
min       1.0000     1.000000    18.000000     0.000000     0.000000   
25%       1.0000    17.000000    32.000000     0.000000     3.000000   
50%       2.0000    34.000000    40.000000     0.000000     9.000000   
75%       3.0000    54.000000    51.000000     1.000000    18.000000   
max       3.0000    72.000000    77.000000     1.000000    55.000000   

            income           ed       employ       retire       gender  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean     77.535000     2.671000    10.987000     0.047000     0.517000   
std     107.044165     1.222397    10.082087     0.211745     0.499961   
min       9.000000     1.000000     0.000000     0.000000     0.000000   
25%      29.000000     2.000000     3.000000     0.000000     0.000000   
50%      47.000000     3.000000     8.000000     0.000000     1.000000   
75%      83.000000     4.000000    17.000000     0.000000     1.000000   
max    1668.000000     5.000000    47.000000     1.000000     1.000000   

            reside      custcat  
count  1000.000000  1000.000000  
mean      2.331000     2.487000  
std       1.435793     1.120306  
min       1.000000     1.000000  
25%       1.000000     1.000000  
50%       2.000000     3.000000  
75%       3.000000     3.000000  
max       8.000000     4.000000

In [ ]:
x=np.asarray(data[data.columns[0:-1]])
y=np.asarray(data[data.columns[-1]])
x0=preprocessing.StandardScaler().fit(x)
x1=x0.transform(x)
x1

array([[-0.02696767, -1.055125  ,  0.18450456, ..., -0.22207644,
        -1.03459817, -0.23065004],
       [ 1.19883553, -1.14880563, -0.69181243, ..., -0.22207644,
        -1.03459817,  2.55666158],
       [ 1.19883553,  1.52109247,  0.82182601, ..., -0.22207644,
         0.96655883, -0.23065004],
       ...,
       [ 1.19883553,  1.47425216,  1.37948227, ..., -0.22207644,
         0.96655883, -0.92747794],
       [ 1.19883553,  1.61477311,  0.58283046, ..., -0.22207644,
         0.96655883, -0.92747794],
       [ 1.19883553,  0.67796676, -0.45281689, ..., -0.22207644,
         0.96655883,  0.46617787]])

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x1,y,test_size=0.2,random_state=10)

In [ ]:
knn = KNeighborsClassifier(n_neighbors=5,metric='minkowski')
y_knn = knn.fit(x_train,y_train)
y_knn_pred = y_knn.predict(x_test)

In [ ]:
knn_acc=accuracy_score(y_test,y_knn_pred)
knn_f1=f1_score(y_test,y_knn_pred,average='micro')

In [ ]:
print("accuracy score ", knn_acc*100, "%")
print("f1_score ", knn_f1*100, "%")

accuracy score  36.0 %
f1_score  36.0 %


In [ ]:
knn_cm=confusion_matrix(y_test,y_knn_pred)
knn_cr=classification_report(y_test,y_knn_pred)
print('confusion matrix\n' , knn_cm)
print('classification report\n', knn_cr)

confusion matrix
 [[31  7 16  9]
 [12  7 13  5]
 [16  8 24  4]
 [13 18  7 10]]
classification report
               precision    recall  f1-score   support

           1       0.43      0.49      0.46        63
           2       0.17      0.19      0.18        37
           3       0.40      0.46      0.43        52
           4       0.36      0.21      0.26        48

    accuracy                           0.36       200
   macro avg       0.34      0.34      0.33       200
weighted avg       0.36      0.36      0.35       200

